# Generated by Django 4.0.1 on 2022-01-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80)),
                ('Specialty', models.CharField(choices=[('dentist', 'dentist'), ('optician', 'optician'), ('chiropractor', 'chiropractor'), ('dermatologist', 'dermatologist')], max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('condition', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctors')),
            ],
        ),
    ]
